version: '3.4'

services:
  socialchitchat.api:
    image: ${DOCKER_REGISTRY-}socialchitchatapi
    container_name: socialchitchat.api
    build:
      context: .
      dockerfile: src/SocialChitChat.Api/Dockerfile
    ports:
      - 5000:5000
      - 5001:5001

  socialchitchat.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: socialchitchat.db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123456
      - MSSQL_PID=Express
    volumes:
      - ./.containers/socialchitchat-db:/var/opt/mssql/data
    ports:
      - 1433:1433

  socialchitchat.cache:
    image: redis:latest
    container_name: socialchitchat.cache
    restart: always
    ports:
      - 6379:6379
